### ISSUE TITLE
Maven output does not  write to the VSC terminal window

### ISSUE THREAD

**Issue by RedWingBB** [microsoft/vscode-maven#489] opened 2020-04-28 15:29 UTC
When I run maven/package a new cmd window is launched and the build output is written to it

I right click the maven project, then Package
A cmd window pops up
The build output streams into it
Then the cmd window closes
This makes it difficult to see if the build succeeded, what were the problems, so on

It may be there is a configuration option in the plugin or in VSC itself that I havent found

Environment is an admin login on  Windows Server 2090
Uploading a screen shot, I hope it shows up.

![image](https://user-images.githubusercontent.com/41631548/80506344-71021f00-8943-11ea-868f-4fcf3fde4bae.png)

**Comment by Eskibear** [comment] 2020-04-29 02:13
The command is expected to run on integrated terminal withing vscode. 
-  What's your vscode's default integrated terminal?

**Comment by Eskibear** [comment] 2020-05-29 02:35
@RedWingBB 
It's probably because you've wronly set `maven.executable.path` by your own.  Please check if the path ends with "mvn.cmd" instead of "mvn".

**Comment by RedWingBB** [comment] 2020-05-29 11:56
Thanks for the reply
Here is my command line
C:\Program Files (x86)\Apache\apache-maven-3.6.3\bin\mvn
My Terminal is Powershell

**Comment by Eskibear** [comment] 2020-05-29 15:24
If the ".cmd" file extension is not specified, powershell will run a CMD propmt in a new window. 

#### What you can do now
Append ".cmd" to "mvn", that it, to set `maven.executable.path` to `C:\Program Files (x86)\Apache\apache-maven-3.6.3\bin\mvn.cmd`. Have a try, and let me know if it works.

**Comment by Eskibear** [comment] 2020-06-12 03:37
Fixed in #499

**Comment by RedWingBB** [comment] 2020-06-16 22:04
Adding .cmd did it
Thanks for the reply

**Comment by Nicryc** [comment] 2021-09-08 11:37
@Eskibear Since the last update of VSCode (August 2021 – 1.60) I'm facing this issue too. 

Maven is forced inside a Powershell __integrated__ terminal (although my default terminal is cmd) and run the following command : `& "path\to\apache-maven-3.2.5\bin\mvn" clean install -f "path\to\pom.xml"` which has for effect to open an __external__ cmd terminal and running Maven inside. Everything was working as intended before this update though, that's really weird.

Adding a `.cmd` to `mvn` just give me a `CommandNotFoundException`

Working on Windows 10. Executed mvn through a right click to the Maven project and used a favourite command defined in `maven.terminal.favorites` : `clean install`

**Comment by Eskibear** [comment] 2021-09-08 13:16
> Since the last update of VSCode (August 2021 – 1.60) I'm facing this issue too.

It's possible that vscode has changed something. Reading release note of the August version, you'll find recently they have been working on terminal related improvement.

> Maven is forced inside a Powershell integrated terminal (although my default terminal is cmd)

True, I can reproduce it. 

> run the following command : & "path\to\apache-maven-3.2.5\bin\mvn" clean install -f "path\to\pom.xml"

I cannot reproduce it, what's your `maven.executable.path`? On my machine, I set it to "C:\apache-maven-3.8.1\bin\mvn", and it ran `PS > & "C:\apache-maven-3.8.1\bin\mvn.cmd" clean -f "path-to-pom.xml"`, appending ".cmd" to "mvn". And it was executed in integrated terminal. 


The "&" was added here when powershell was detected as default shell:

https://github.com/microsoft/vscode-maven/blob/64d576444021b0658d57dee32bc3a0d87179b711/src/mavenTerminal.ts#L101-L103

And the terminal is created using vscode's API, which should also use default shell. You mentioned a Powershell was used, and that looks consistent with above "&" behavior.

The problem is, why ".cmd" was not appended to your "mvn". Because it's also intentionally done for Powershell in #499

https://github.com/microsoft/vscode-maven/blob/64d576444021b0658d57dee32bc3a0d87179b711/src/mavenTerminal.ts#L59-L69


#### Actions for you to take

Please help to check below:
* What's your `maven.executable.path` setting?
* Do you have path\to\apache-maven-3.2.5\bin\mvn**.cmd** on your filesystem?
* What's you OS and how do you launch VS Code (desktop/web/codespaces/remote container/WSL/etc...)?

**Comment by Nicryc** [comment] 2021-09-11 17:20
- My `maven.executable.path` : `C:\Users\nicryc\Documents\Programmes portables\apache-maven-3.2.5\bin\mvn`   
- I don't have a `mvn.cmd` in my filesystem.  
- I'm running Windows 10 and VS Code desktop.

I have downloaded my Maven version [here](https://archive.apache.org/dist/maven/maven-3/3.2.5/binaries/) and it doesn't provide a `mvn.cmd`.

**Comment by Eskibear** [comment] 2021-09-12 11:05
@Nicryc Thanks for the information. I can reproduce it now.

> I don't have a mvn.cmd in my filesystem.

True. The problem is maven-3.2.5 use `mvn.bat` instead of `mvn.cmd`. I'll fix that ASAP.

For the moment you can set `maven.executable.path` to `C:\Users\nicryc\Documents\Programmes portables\apache-maven-3.2.5\bin\mvn.bat` as a workaround.

**Comment by Eskibear** [comment] 2021-09-14 15:55
> For the moment you can set maven.executable.path to C:\Users\nicryc\Documents\Programmes portables\apache-maven-3.2.5\bin\mvn.bat as a workaround.

@Nicryc I simply provided a fix appending ".bat" or ".cmd" accordingly, covering your case. Please kindly let me know if that works for you. Thanks.

**Comment by Eskibear** [comment] 2021-09-22 09:06
will be shipped in 0.34.0.


To verify:
1. download a **maven-3.2.5** distribution, and extract somewhere
2.  set `maven.executable.path` to "<path-to-maven-3.2.5>/bin/mvn"    (**without file extension**)
3. change vscode default shell to PowerShell.
4. Run maven commands, e.g. `clean` , see if it works.

**Comment by Eskibear** [comment] 2021-09-24 07:37
mitigated in v0.34.0

**Closed by Eskibear** 2021-09-24 07:37 UTC

**Comment by Nicryc** [comment] 2021-09-24 19:36
Ok this is working like a charm. Thanks.
