### ISSUE TITLE
Show Dependencies failed but mvn can list the project dependencies successfully

### ISSUE THREAD

**Issue by CsCherrYY** [microsoft/vscode-maven#887] opened 2022-10-12 03:29 UTC
**To Reproduce**
1. Git clone https://github.com/wfh45678/radar.git
2. Open in VS Code, expand maven view, right click project `radar-dao`, and choose `Show Dependencies`.
3. There should be an error notification.
![image](https://user-images.githubusercontent.com/45906942/195243107-2d557091-91d9-4bfe-8b17-227da81c7aad.png)
5. directly use `mvn dependency:tree` in the project
6. The dependencies of the given project has been printed successfully.
![image](https://user-images.githubusercontent.com/45906942/195243231-c342b471-be5a-4cd1-bae4-bd3f580154fc.png)

**Expected behavior**
Show Dependencies should show the dependencies of the project successfully.

**Comment by Askeiter** [comment] 2022-10-14 10:57
It happens to me or I have installed the latest version of everything on a new PC, but when I try to see the dependency tree from the maven explorer it gives an error, and it does not tell me what error it gives
![image](https://user-images.githubusercontent.com/1458540/195829612-5c76241f-9b8f-4083-b9f1-fa37ece5a638.png)

![image](https://user-images.githubusercontent.com/1458540/195829767-f1010c4c-dee9-45e9-8798-e67c193df623.png)

the command palette option has also disappeared

![image](https://user-images.githubusercontent.com/1458540/195830014-35429ac8-44c0-4bcd-9988-4196bad96121.png)

![image](https://user-images.githubusercontent.com/1458540/195830162-8c1fd10f-e22d-4517-b7f1-958ab4ba315d.png)

only the context menu works


![image](https://user-images.githubusercontent.com/1458540/195830873-8b6295d2-402e-4b78-a650-012c3c37b887.png)

**Comment by Eskibear** [comment] 2022-10-14 16:03
@Askeiter 
It somehow failed to render diagnotics for dependency conflicts, but we are not able to reproduce it so far. See https://github.com/microsoft/vscode-maven/issues/815 

Can you provide a sample project, and the content in "Dependencies"?

**Comment by Askeiter** [comment] 2022-10-17 09:19
Hi, I can't provide a project repository, they are private projects on a company intranet.
I have read the issue 815, and it seems that it is the same case, but I am not sure,

**Comment by Eskibear** [comment] 2022-10-17 15:13
If you can provide a minimal sample project to reproduce the issue, that would be helpful for me to fix it.
Maybe it's due to some magic combination of artifacts from the dependencies that we didn't cover well. You may search "conflict" in the Dependencies generated by this extension.

**Comment by Eskibear** [comment] 2022-10-24 02:47
@Askeiter Or you can switch to [pre-release](https://code.visualstudio.com/updates/v1_63#_pre-release-extensions) version, see if that's already fixed by PR #883

**Comment by Askeiter** [comment] 2022-10-27 11:04
I can confirm that after changing the preliminary version the problems have been resolved, as you can see in the image the entire project compiles, you can now expand and see the dependencies
![image](https://user-images.githubusercontent.com/1458540/198268154-22951b6b-1e30-4e99-abbd-c4ef9b73626c.png)

![image](https://user-images.githubusercontent.com/1458540/198268039-1ba3a9b7-2ceb-4605-8d16-fa1524ae5f12.png)

**Closed** 2023-03-17 04:32 UTC
