### ISSUE TITLE
Unable to create Maven Java project in VS Code

### ISSUE THREAD

**Issue by post-war** [microsoft/vscode-maven#941] opened 2023-02-27 10:31 UTC
I am unable to create Maven java project from archetype in VS code. I have given below the error I get. I have searched and found many have reported the same since 2019. I have tried all the suggested solutions but to no avail.
![image](https://user-images.githubusercontent.com/81802101/221539811-b8cf1b1a-056b-4050-83a6-952ff089c768.png)
I am using Windows 10.

**Comment by post-war** [comment] 2023-02-28 11:44
I tried after removing outer quotes, but different errors. ( fyi, I can create Maven project in another pc without errors)
I think the command is correct. It starts executing but gets into some errors, full log is below.
 *  Executing task: ""c:\Users\arxn.CPAA.001\.vscode\extensions\vscjava.vscode-maven-0.40.4\resources\maven-wrapper\mvnw.cmd" org.apache.maven.plugins:maven-archetype-plugin:3.1.2:generate -DarchetypeArtifactId="maven-archetype-quickstart" -DarchetypeGroupId="org.apache.maven.archetypes" -DarchetypeVersion="1.4" -DgroupId="com.example" -DartifactId="demo" -DoutputDirectory="c:\Users\arxn.CPAA.001\my proj"" 

Exception in thread "main" java.net.UnknownHostException: repo.maven.apache.org
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:607)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:293)
        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)    
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:203)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1572)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1500)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
        at org.apache.maven.wrapper.DefaultDownloader.downloadInternal(DefaultDownloader.java:90)
        at org.apache.maven.wrapper.DefaultDownloader.download(DefaultDownloader.java:76)  
        at org.apache.maven.wrapper.Installer.createDist(Installer.java:72)
        at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:121)      
        at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:61)        

 *  The terminal process "cmd.exe /c ""c:\Users\arxn.CPAA.001\.vscode\extensions\vscjava.vscode-maven-0.40.4\resources\maven-wrapper\mvnw.cmd" org.apache.maven.plugins:maven-archetype-plugin:3.1.2:generate -DarchetypeArtifactId="maven-archetype-quickstart" -DarchetypeGroupId="org.apache.maven.archetypes" -DarchetypeVersion="1.4" -DgroupId="com.example" -DartifactId="demo" -DoutputDirectory="c:\Users\arxn.CPAA.001\my proj""" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it.

**Comment by post-war** [comment] 2023-02-28 12:02
No firewall issue as I can reach https://repo.maven.apache.org/ from browser

**Comment by Eskibear** [comment] 2023-02-28 12:58
I don't see such error, using the same `mvnw` embedded in this extension, as below. From the error log you provided, it's likely related to your networking status, e.g. are you behind some proxy/VPN, or some self-issued certs required, etc... The root cause should be that "repo.maven.apache.org" failed to be resolved. I myself guess it's related to DNS/SSL certs.

![image](https://user-images.githubusercontent.com/2351748/221859788-71d7be90-3152-432b-b83e-386a2bdaad7d.png)

**Comment by Eskibear** [comment] 2023-02-28 13:00
Or you can download a Maven distribution on your own, and add it into `PATH` env. use `mvn` to run almost the same command in CMD, see if it works. If it works, we have a setting `maven.executable.path` for you to specify.

**Comment by post-war** [comment] 2023-02-28 22:23
Thanks, DNS/SSL cert must be the likely cause. I will try with mvn directly.

**Comment by Eskibear** [comment] 2023-03-22 02:35
I'm closing it as it's probably networking issue. Feel free to reopen it if anything new is found.

**Closed by Eskibear** 2023-03-22 02:35 UTC

**Comment by BharathKalva69** [comment] 2023-11-30 09:56
> I am unable to create Maven java project from archetype in VS code. I have given below the error I get. I have searched and found many have reported the same since 2019. I have tried all the suggested solutions but to no avail. ![image](https://user-images.githubusercontent.com/81802101/221539811-b8cf1b1a-056b-4050-83a6-952ff089c768.png) I am using Windows 10.

I am facing the same somebody help me to solve this please, this error is haunting me, and my project dead is approaching (panik!). thanks

**Comment by BharathKalva69** [comment] 2023-11-30 09:56
> You can copy the full command (`cmd.exe /c ""......my proj""`), run it in an external cmd prompt. See if that would work or any error?

Did it, nothing happened.

**Comment by sindhiyas** [comment] 2024-04-10 05:47
I am facing the same issue as mentioned above. can somebody please help with some solutions. thanks
