### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by reporter123** [Microsoft/vscode-maven#241] opened 2019-02-01 13:50 UTC
- Issue Type: `Performance`
- Extension Name: `vscode-maven`
- Extension Version: `0.14.1`
- OS Version: `Linux x64 4.18.0-13-generic`
- VSCode version: `1.30.2`

[vscjava.vscode-maven-unresponsive.cpuprofile.txt](https://github.com/Microsoft/vscode-maven/files/2821796/vscjava.vscode-maven-unresponsive.cpuprofile.txt)

This issue manifests intermittently on startup opening a workspace containing no java or maven.

**Comment by Eskibear** [comment] 2019-02-01 16:00
@reporter123 Thanks for reporting. I had a glance of the cpuprofile, but cannot figure out the reason. 

> opening a workspace containing no java or maven.
It's strange, and the extension should not be activated. AFAIK the extension is activated only for either of the following conditions: a) have pom.xml in your workspace. b) open a pom.xml (even if it's not within the workspace). c) Manually trigger related command or expand the Maven explorer. 

Can you help to identify whether Maven extension is activated or not when opening your workspace. 
![image](https://user-images.githubusercontent.com/2351748/52133033-88d4ef80-267b-11e9-849b-a79f75a33e77.png)


BTW, other users reported this [before](https://github.com/Microsoft/vscode-maven/issues/192), and I've removed all the operation with potential high cpu risk I can think of. But to be honest I cannot find out the root cause. And searching in GitHub, the [results ](https://github.com/search?q=Extension+causes+high+cpu+load&type=Issues) reveals that the issue occurs for lots of extensions and almost no one knows the reason. I find in most of them , the OS is `Linux X64 4.18.0-xxxx`, and I'm not sure whether it's clue or not.

**Comment by reporter123** [comment] 2019-02-10 00:20
![image](https://user-images.githubusercontent.com/684470/52527911-a7b13280-2cc8-11e9-8499-6d4bcd9c5c14.png)

This screen shot was taken after startup with no interaction with code beyond executing the "show running Exentions" command. If you need to source for my project its here https://cgit.kde.org/kdiff3.git/tree/.

**Comment by Eskibear** [comment] 2019-02-10 08:32
I cloned your project, and the Maven extension is **not** activated, as expected. 
![image](https://user-images.githubusercontent.com/2351748/52531434-885de800-2d50-11e9-9d3c-364450a34e52.png)

In your screenshot, the extension was activated on **startup**. Among the [activation events](https://github.com/Microsoft/vscode-maven/blob/b427c38b3f3938a3e5d71fc91101ec63525475d5/package.json#L26-L47), the only possibility for a **"Startup Activation"** is `"workspaceContains:**/pom.xml"`, I think you might need to double check if there's any pom.xml in your workspace.

**Comment by reporter123** [comment] 2019-02-13 03:55
For the record.
![image](https://user-images.githubusercontent.com/684470/52685747-ccb0da00-2f42-11e9-9100-bf6744b2a9ab.png)

I suspect its an interaction with some other extension that's triggering the activation some how.

**Comment by Eskibear** [comment] 2019-02-13 06:06
> I suspect its an interaction with some other extension that's triggering the activation some how.

It's against the fact that it's a "Startup Activation". 

It's strange, I cannot provide any more information for the moment. And if you still suffer from it, you can disable the extension for the workspace only.

**Comment by Eskibear** [comment] 2019-03-27 01:25
Closing it, see https://github.com/Microsoft/vscode-java-pack/issues/81#issuecomment-476457431

**Closed by Eskibear** 2019-03-27 01:25 UTC
Labels: help wanted
