### ISSUE TITLE
UI Distortion in Explorer-Maven When Closing 'plugins' after Opening Project

### ISSUE THREAD

**Issue by jianggujie1** [microsoft/vscode-maven#1013] opened 2023-12-14 01:35 UTC
## Issue Title
UI Distortion in Explorer-Maven When Closing 'plugins' after Opening Project

## Description

In Visual Studio Code, using the Maven for Java plugin, I've encountered an issue where, after opening a project, expanding the "plugins" section in the Explorer's Maven view and subsequently closing it results in UI distortion. 

![屏幕截图 2023-12-14 093302](https://github.com/microsoft/vscode-maven/assets/23006994/d6d031cf-faf5-46c4-890f-5382207b734d)

## Steps to Reproduce

1. Open Project X.
2. In the Explorer's Maven view, expand the "plugins" section.
3. Close the "plugins" section.
4. Observe the UI distortion [provide details on the distortion observed].

## Environment Information

- Maven for Java Plugin Version: v0.43.0
- Visual Studio Code Version: 1.85.1
- Operating System: Windows 11 pro 22H2

## Expected Behavior

The expected behavior is that the UI remains normal after closing the "plugins" section, without any distortion.

**Comment by AnskCat** [comment] 2023-12-14 13:09
Having same issue. 

<img width="1487" alt="image" src="https://github.com/microsoft/vscode-maven/assets/105315705/6353d5e8-d7c9-4cd5-bed1-0f61c3ae02ff">

Environment Information
-----

- Maven for Java Plugin Version: v0.43.0
- Visual Studio Code Version: November 2023 (version 1.85)
- OS: macOS Sonoma Version 14.2
- Chip: Apple M1 Pro

**Comment by vanchKong** [comment] 2023-12-23 16:07
Having same issue.

**Comment by haogaulle** [comment] 2023-12-27 17:06
Having same issue.

**Comment by bylwong** [comment] 2023-12-27 19:31
Seems to be degraded in latest vscode version 1.85.1. Worked fine in 1.84.2.

Verified working combination:
Maven for Java Version: v0.43.0
Visual Studio Code Version: 1.84.2

**Comment by paulzhn** [comment] 2024-01-02 13:54
Having the same issue, hope to fix it

**Comment by testforstephen** [comment] 2024-01-03 04:49
I can reproduce this issue in vscode@1.85.1 as well, this is a bug in the upstream VS Code. The latest insiders seems fixed it, and I tried the latest vscode-insider@1.86.0 (https://code.visualstudio.com/insiders/) again, it works fine. Could you try the latest vscode-insider and let me know whether it works? thanks.

**Comment by LucasMRC** [comment] 2024-01-11 14:19
Having same issue

**Comment by dorabra** [comment] 2024-01-16 14:56
Having it too, plus it does not display the lower levels of options in each of the plugins. 

Please find a solution 🙏.

**Comment by testforstephen** [comment] 2024-01-17 01:48
> Having same issue in Insiders 1.86.0

@LucasMRC What insider version do you use?

**Comment by testforstephen** [comment] 2024-01-17 01:49
> Having it too, plus it does not display the lower levels of options in each of the plugins.
> 
> Please find a solution 🙏.

This issue has been fixed by upstream VS Code. It's in the latest vscode-insider, please try it. @dorabra

**Closed by testforstephen** 2024-01-17 01:49 UTC
Labels: bug, upstream
