### ISSUE TITLE
Unable to run maven commands after restarting computer.

### ISSUE THREAD

**Issue by brendonparker** [microsoft/vscode-maven#788] opened 2022-02-07 14:00 UTC
**Describe the bug**
I'm new to Java to bear with me...
The extension was working great Friday, but after restarting my laptop, all the maven commands are failing with:

```
PS C:\DEV\javaDemo> & "c:\DEV\javaDemo\mvnw.cmd" package -f "c:\DEV\javaDemo\pom.xml"
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:47)
        at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:156)
        at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:72)
Caused by: java.lang.NoClassDefFoundError: org/apache/maven/exception/ExceptionHandler
        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
        at java.base/java.lang.Class.getMethodsRecursive(Class.java:3307)
        at java.base/java.lang.Class.getMethod0(Class.java:3293)
        at java.base/java.lang.Class.getMethod(Class.java:2106)
        at org.codehaus.plexus.classworlds.launcher.Launcher.getEnhancedMainMethod(Launcher.java:168)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:261)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
        ... 7 more
Caused by: java.lang.ClassNotFoundException: org.apache.maven.exception.ExceptionHandler
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
        ... 17 more
```

**To Reproduce**
1. Install JDK
2. Install VS Code
3. Install _Extension Pack for Java_ in Vs Code
4. Run mvn package (works)
5. Restart computer
6. Run mvn package (fails)

**Expected behavior**
Expect mvn package to not fail

**Environments (please complete the following information as much as possible):**
 - OS: Windows 10
 - VS Code version: 1.64.0
 - Extension version 0.35.0

**Screenshots**
N/A

**Additional context**
N/A

**Comment by brendonparker** [comment] 2022-02-07 16:08
I was able to get it back operational by doing the following steps:
1. Uninstalling the extension
2. Closing all instances of VS Code
3. Deleting `C:\Users\Administrator\.m2`
4. Deleting `target` folder in project
5. Re-installing extension

Not sure if all steps were required. But that did the trick. I'll post an update if I run into the issue again.

**Comment by Eskibear** [comment] 2022-02-09 00:49
> Deleting C:\Users\Administrator\.m2

It's probably because some broken jars have been downloaded into .m2 folder, and this step did the trick.

If you run into the issue again, please try running mvn commands in terminal outside vscode. That would tell whether it's vscode's issue or not.

I'm closing this issue now, and feel free to re-open and update details if you reproduce it later.

**Closed by Eskibear** 2022-02-09 00:49 UTC
