### ISSUE TITLE
Maven profiles not managed

### ISSUE THREAD

**Issue by loryx636** [Microsoft/vscode-maven#117] opened 2018-08-30 13:03 UTC
**Describe the bug**
If VS Code is open, and from a terminal (internal or external) launch the execution of the project with "mvnw -PprofileName", the execution exclude the profile, using the default configuration in pom.xml.

**Expected behavior**

**Environments (please complete the following information as much as possible):**
 - OS: Windows 7

**Comment by Eskibear** [comment] 2018-09-01 15:34
Currently you can add "-PprofileName" to entry "maven.executable.options" in settings, e.g. in workspace settings. Then it appends the string when constructing commands.

![image](https://user-images.githubusercontent.com/2351748/44947404-49da0e00-ae3f-11e8-907b-142a35e9b317.png)

**Comment by loryx636** [comment] 2018-10-01 14:53
I try to do this configuration, in user settings, or workspace settings, but without success. The only way to accomplish this is to add the entry on settings.xml under .m2, but this add the same profile to all projects.
![immagine](https://user-images.githubusercontent.com/24590027/46296353-7a29df00-c59a-11e8-87de-85ddf8fb8f9c.png)

**Comment by Eskibear** [comment] 2018-11-23 02:02
@loryx636 I think it might be the issue of mvnw/mvn, the extension only concat commands for users.  What if VS Code is NOT open? Does the maven wrapper work well?

**Comment by Eskibear** [comment] 2018-11-23 02:13
BTW I don't see any problem activating a profile. The value of a property specified in my profile is correct.

![image](https://user-images.githubusercontent.com/2351748/48926334-eaecd800-ef07-11e8-8c4f-0fa5bbf99fd0.png)

Closing it now. Feel free to re-open it and provide steps to reproduce if you still have the issue.

**Closed by Eskibear** 2018-11-23 02:13 UTC
Labels: discussion

**Comment by helsonxiao** [comment] 2019-10-03 15:22
I'm developing in my local docker container. Docker image starts with `docker-dev` profile by default and it works fine after I execute `mvn compile -Pdocker-dev`. However, when I save files in VS Code, this plugin will choose another profile(active by default) even if I add the options.

![image](https://user-images.githubusercontent.com/26411634/66139689-71e40400-e633-11e9-9668-da3c8a9ecf70.png)

```
    <profile>
      <id>dev</id>
      <properties>
        <spring.profiles.active>dev</spring.profiles.active>
      </properties>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
    </profile>
```
I tried to remove above activation config. This plugin then chose the default profile and failed to run.

**Comment by helsonxiao** [comment] 2019-10-24 16:31
> I'm developing in my local docker container. Docker image starts with `docker-dev` profile by default and it works fine after I execute `mvn compile -Pdocker-dev`. However, when I save files in VS Code, this plugin will choose another profile(active by default) even if I add the options.
> 
> ![image](https://user-images.githubusercontent.com/26411634/66139689-71e40400-e633-11e9-9668-da3c8a9ecf70.png)
> 
> ```
>     <profile>
>       <id>dev</id>
>       <properties>
>         <spring.profiles.active>dev</spring.profiles.active>
>       </properties>
>       <activation>
>         <activeByDefault>true</activeByDefault>
>       </activation>
>     </profile>
> ```
> 
> I tried to remove above activation config. This plugin then chose the default profile and failed to run.
> 
> `No active profile set, falling back to default profiles: default`
> 
> P.S.
> VS Code Version: 1.38.1
> Maven for Java: 0.19.1

I've found the problem. I installed the Java Extension Pack which includes this plugin in VSCode. However, some of them will force build the project when you change files and build without options(like -Pdev or something else you set).

**Comment by Eskibear** [comment] 2019-10-28 00:42
I guess it's [vscode-java](https://github.com/redhat-developer/vscode-java)'s setting `java.configuration.updateBuildConfiguration`. When you set the value to "automatic", it auto build the maven project according to your pom.xml whenever changes are detected. And `maven.executable.options` is a setting of this Maven extension, which is not honored by vscode-java. This setting only affects the maven commands we assemble and send to the terminal.

**Comment by spaghett1c0de** [comment] 2020-03-30 08:07
@Eskibear I ran into the exact same issue and debugged this for a couple of hours only to realize that it was VS Code. If I quit VS Code, then the command works perfectly. When VS Code is open, it simply ignores the -Pprofile flag and uses the default profile specified in the POM. Not sure if there's a fix for this.

**Comment by Eskibear** [comment] 2020-03-31 02:39
@spaghett1c0de 
It sounds strange. As there are a bunch of Java-related extensions, I cannot tell if it's exactly caused by this extension. Can you try disabling all the other extensions (i.e. only enabling **Maven for Java**), see if the issue still exists?

**Comment by spaghett1c0de** [comment] 2020-03-31 05:58
@Eskibear 
That's a great suggestion! I just tested it by disabling every Java extension and left with **Maven for Java**. It works correctly. 😮 So I tried to enable each of them one by one to see what caused this. 🤔And surprisingly, it's [**Language Support for Java(TM) by Red Hat**](https://github.com/redhat-developer/vscode-java) extension that is causing this issue. I tested a few times, and I can confirm that this extension somehow causes the maven commands to ignore the -Pprofile flag and uses the default profile specified in the POM.

**Comment by Eskibear** [comment] 2020-03-31 10:08
Good finding. So you might be experiencing the same issue mentioned in https://github.com/microsoft/vscode-maven/issues/117#issuecomment-537993266

I'll suggest that you open an issue in their repo. But you may have a try with the setting `java.configuration.updateBuildConfiguration` to temporarily disable auto build.

**Comment by spaghett1c0de** [comment] 2020-04-01 08:14
@Eskibear 
I'll go ahead and post an issue in their repo and see if that gets resolved.

I tried disabling `java.configuration.updateBuildConfiguration` and it didn't work. :/
