### ISSUE TITLE
I can't create maven projects in workspace

### ISSUE THREAD

**Issue by 1516203584** [microsoft/vscode-maven#689] opened 2021-08-02 13:35 UTC
When I use workspace, it will not work, but when I do not use it, it works normally.

**Comment by Eskibear** [comment] 2021-08-03 04:00
I cannot reproduce it. Please provide more information about the steps to reproduce it. 

FYI with a workspace opened, I just successfully created a new maven project. 
![image](https://user-images.githubusercontent.com/2351748/127955477-60af0dc6-b3ae-490c-9d36-521448b093cd.png)

**Comment by 1516203584** [comment] 2021-08-03 10:05
> I cannot reproduce it. Please provide more information about the steps to reproduce it.
> 
> FYI with a workspace opened, I just successfully created a new maven project.
> ![image](https://user-images.githubusercontent.com/2351748/127955477-60af0dc6-b3ae-490c-9d36-521448b093cd.png)

![捕获](https://user-images.githubusercontent.com/60887371/127997376-7b584f3d-a027-4e0d-868a-0586503372e1.PNG)
I use windows11 to run the visual studio code's last version.
When I use Creating Java Projects to create java projects, I use Maven to create.
And then, it shows the image.
![捕获2](https://user-images.githubusercontent.com/60887371/127997383-2cb042af-bdfa-45f7-ad59-55004d09c38f.PNG)

**Comment by 1516203584** [comment] 2021-08-03 12:10
@Eskibear

**Comment by 1516203584** [comment] 2021-08-03 13:17
I am successful.Thank you very much!.

**Comment by 1516203584** [comment] 2021-08-03 13:40
The problem is because the workspace needs to add a folder into workspace.

**Comment by Eskibear** [comment] 2021-08-03 18:44
> The problem is because the workspace needs to add a folder into workspace.

@jdneo it can be an edge case we didn't cover. please take a look.

**Comment by Eskibear** [comment] 2021-08-13 03:14
fixed in 0.32.2

**Closed by Eskibear** 2021-08-13 03:14 UTC
