### ISSUE TITLE
XML comment does not work with this extention

### ISSUE THREAD

**Issue by hemangajmera** [microsoft/vscode-maven#422] opened 2019-11-08 07:43 UTC
**Describe the bug**
When I hit `Ctrl /` I expect comment to be added for standard XML by enclosing selection or line in `<!--` and `-->`. Instead `//` is added in front of line (java code). If I remove this extension VSCode comments behaves properly

**To Reproduce**
1. Open pom.xml
2. Do Ctrl /

**Expected behavior**
Proper XML comments

**Environments (please complete the following information as much as possible):**
 - Windows 10 (1703)
 - VS Code version: Version: 1.39.2 (user setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.15063

 - Extension version: 0.19.1

**Screenshots**

**Additional context**
Following other extensions are installed
![image](https://user-images.githubusercontent.com/308006/68458666-5b7c2a00-0229-11ea-8be6-53679beeee7d.png)
![image](https://user-images.githubusercontent.com/308006/68458687-69ca4600-0229-11ea-8b51-c453ce3ebcda.png)
![image](https://user-images.githubusercontent.com/308006/68458700-7189ea80-0229-11ea-9ef8-d5ae50421274.png)

**Comment by Eskibear** [comment] 2019-11-11 03:20
I cannot reproduce it. It works well for me whether this Maven extension is enabled/disabled. 
Can you try disabling all the other installed extensions, and see if the issue still exists? 

![image](https://user-images.githubusercontent.com/2351748/68558600-f1f05b80-0474-11ea-9b22-b0c4b3ca4b6c.png)

**Comment by hemangajmera** [comment] 2019-11-14 10:52
When I disable this extension, comment worked fined. When I enabled it, it didn't work as expected. It might be that combination of extensions causing this issue. Is there a better way to debug the issue then enabling/disabling extensions one by one?

**Comment by hemangajmera** [comment] 2019-11-14 13:15
One more observation. If pom.xml file is opened in previous session. Then comments doesnt work properly. So in step to reproduce, we need to open pom.xml, close vscode and open vscode again. Now since pom.xml was open in previous session, it will be open and at this time the comment will not work properly

**Comment by hemangajmera** [comment] 2019-11-14 13:38
One more observation. This happens only when redhat.vscode-xml and vscjava.vscode-maven are both installed and enabled. Each one works fine.

**Comment by Eskibear** [comment] 2019-11-14 16:31
See my screenshot above, there is a command "Disable All Installed Extensions for this Workspace", which disable ALL extensions. Then reload window, and ONLY enable Maven extension, see if the issue still exists. (I believe not, but please share your result.)

> Is there a better way to debug the issue then enabling/disabling extensions one by one?

Following above steps, now you can enable OTHER extensions one by one, to find out if there is a culprit.

**Comment by hemangajmera** [comment] 2019-11-16 17:11
With only maven plug-in, the effect is not happening. As I said, this happens only when there is combination of plug-in. 

Sent from Yahoo Mail on Android 
 
  On Thu, Nov 14, 2019 at 10:01 PM, Yan Zhang<notifications@github.com> wrote:   
See my screenshot above, there is a command "Disable All Installed Extensions for this Workspace", which disable ALL extensions. Then reload window, and ONLY enable Maven extension, see if the issue still exists. (I believe not, but please share your result.)


Is there a better way to debug the issue then enabling/disabling extensions one by one?


Following above steps, now you can enable OTHER extensions one by one, to find out if there is a culprit.

**Comment by Eskibear** [comment] 2019-11-18 01:40
As I said, I pointed a way to help you find out which extension is conflicting with Maven extension. I don't have time to test EVERY extension blindly to verify if there's any issue, hope you can understand that. Without enough information to reproduce the issue on my side, I'm closing this issue now, and feel free to re-open it when you find out the culprit.

**Closed by Eskibear** 2019-11-18 01:40 UTC
