### ISSUE TITLE
Update Maven Archetype Catalog Error

### ISSUE THREAD

**Issue by debugbb** [Microsoft/vscode-maven#274] opened 2019-03-11 08:20 UTC
1、Ctrl+Shift+P->Update Maven Archetype Catalog
2、
![image](https://user-images.githubusercontent.com/6327466/54109427-9b300f00-4419-11e9-9114-75fff0d0c898.png)

**Comment by Eskibear** [comment] 2019-03-11 14:51
I cannot reproduce it on my local machine. Can you share the callstack or the cpuprofile?
E.g. for the call stack, you can see it by executing <kbd>Ctrl + Shift + P</kbd> -> "Toggle Developer Tools".

**Comment by Eskibear** [comment] 2019-03-15 06:45
v0.15.1 has been released with the fix.

**Closed by Eskibear** 2019-03-15 06:45 UTC
Labels: needs more info
