### ISSUE TITLE
Running mvn package -Ptest uses the activeByDefualt instead of the "test" profile

### ISSUE THREAD

**Issue by thetanked** [Microsoft/vscode-maven#175] opened 2018-12-12 21:43 UTC
**Describe the bug**
So when I am running vscode with the Maven for Java Extension enabled I try running mvn clean package -Ptest but what actually runs is the profile that has the tag <activeByDefault>true</activeByDefault> 

If I remove the active tag, it works

If I write false to it, it works 

If I disable the extension, it works

If I close vscode with or without the extension being enabled, it works

**To Reproduce**
For me case:
1. open a terminal  (I am using git bash**)
2. Run the command above 
3. Look at target folder and see resources and other things missing or added that should not be there. 

**Expected behavior**
Would expect it to run as if I did not have the extension running. 

**Environments (please complete the following information as much as possible):**
 - OS: Windows 10
 - VS Code version: 1.22.2
 - Extension version 0.7.0

** I opened a git bash terminal outside of vscode and the command worked also works inside vscode with the extension disabled. 

I do know there was a similar post on here (Maven profiles not managed #117) that has been closed for close to a month that is similar to my current issue.

**Comment by Eskibear** [comment] 2018-12-13 02:08
@thetanked Thanks for the detailed information. Are you able to upgrade VSCode and Maven extension to the latest version, and see if the issue still exists?

**Comment by thetanked** [comment] 2018-12-13 04:40
Unfortunately I am not able to. I would love to and it was my first thought. Unfortunately I am unable to upgrade.

**Comment by Eskibear** [comment] 2018-12-13 15:56
@thetanked I’ll take a look, see if the issue exists in the current version. Btw if you are not able to upgrade, even if I fix the bug(if there is one) you still cannot get it, right?

**Comment by thetanked** [comment] 2018-12-14 15:12
@Eskibear I am not sure I might be able to talk someone into giving me permissions to upgrade it. The thing is that this extension is just a that and extension. So I can do my work without it. It is just convenient for me to use it inside of VScode

**Comment by Eskibear** [comment] 2019-01-15 07:07
![image](https://user-images.githubusercontent.com/2351748/51163784-ce509900-18d5-11e9-8c73-e2cdace3d4e9.png)

I'm not able to reproduce it. Can it be a Maven issue (what's the version)? As I mentioned in #117 , the extension only assembles the command for you, and it does no tricky things. The only possibility I can think of is that you might have set some envs in `"maven.terminal.customEnv"` settings, which would be set before an integrated terminal is launched.  

I'm using:
Apache Maven 3.5.4 (picked by mvnw)
VS Code 1.30.2
VS Code Maven extension 0.13.0

I'm closing it now. Feel free to re-open if you find any new clues.

**Closed by Eskibear** 2019-01-15 07:07 UTC
